---
version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/matterbridge'
    schedule:
      interval: 'daily'
    commit-message:
      prefix: 'chore: '

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'
    commit-message:
      prefix: 'chore: '
