---
build_from:
  i386: ghcr.io/hassio-addons/base:15.0.8
  amd64: ghcr.io/hassio-addons/base:15.0.8
  aarch64: ghcr.io/hassio-addons/base:15.0.8
codenotary:
  base_image: l2jliga@gmail.com
  signer: l2jliga@gmail.com
