---
build_from:
  i386: ghcr.io/hassio-addons/base:16.1.3
  amd64: ghcr.io/hassio-addons/base:16.1.3
  aarch64: ghcr.io/hassio-addons/base:16.1.3
codenotary:
  base_image: l2jliga@gmail.com
  signer: l2jliga@gmail.com
