---
build_from:
  i386: ghcr.io/hassio-addons/base:17.2.4
  amd64: ghcr.io/hassio-addons/base:17.2.4
  aarch64: ghcr.io/hassio-addons/base:17.2.4
codenotary:
  base_image: l2jliga@gmail.com
  signer: l2jliga@gmail.com
