---
build_from:
  i386: ghcr.io/hassio-addons/base:16.2.1
  amd64: ghcr.io/hassio-addons/base:16.3.6
  aarch64: ghcr.io/hassio-addons/base:16.3.6
codenotary:
  base_image: l2jliga@gmail.com
  signer: l2jliga@gmail.com
