---
build_from:
  i386: ghcr.io/hassio-addons/base:17.2.5
  amd64: ghcr.io/hassio-addons/base:17.2.5
  aarch64: ghcr.io/hassio-addons/base:17.2.5
codenotary:
  base_image: l2jliga@gmail.com
  signer: l2jliga@gmail.com
