---
build_from:
  i386: ghcr.io/hassio-addons/base:19.0.0
  amd64: ghcr.io/hassio-addons/base:19.0.0
  aarch64: ghcr.io/hassio-addons/base:19.0.0
codenotary:
  base_image: l2jliga@gmail.com
  signer: l2jliga@gmail.com
