---
build_from:
  i386: ghcr.io/hassio-addons/base:15.0.7
  amd64: ghcr.io/hassio-addons/base:15.0.7
  armv7: ghcr.io/hassio-addons/base:15.0.7
  armhf: ghcr.io/hassio-addons/base:15.0.7
  aarch64: ghcr.io/hassio-addons/base:15.0.7
codenotary:
  base_image: l2jliga@gmail.com
  signer: l2jliga@gmail.com
