---
name: CI

# yamllint disable-line rule:truthy
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  workflow_dispatch:

jobs:
  workflows:
    uses: L2jLiga/ha-addons/.github/workflows/addon-ci.yaml@master

  automerge:
    name: 'Merge Dependabot updates'
    if: github.event_name == 'pull_request'
    needs:
      - workflows
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - uses: fastify/github-action-merge-dependabot@v3.10.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
