---
name: CI

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  workflow_dispatch:

jobs:
  workflows:
    uses: L2jLiga/ha-addons/.github/workflows/addon-ci.yaml@master

  release:
    if: github.event_name != 'pull_request'
    needs:
      - workflows
    runs-on: ubuntu-latest
    steps:
      - name: Automatic Semver Release
        uses: rui-costa/action-automatic-semver-releases@1.1.1
        with:
          TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          SEMVER: "PATCH"
          LABEL: ""

  automerge:
    name: 'Merge Dependabot updates'
    if: github.event_name == 'pull_request'
    needs:
      - workflows
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - uses: fastify/github-action-merge-dependabot@v3.9.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
