---
name: Deploy

# yamllint disable-line rule:truthy
on:
  release:
    types:
      - published
  workflow_run:
    workflows: ["CI"]
    branches: [main]
    types:
      - completed

jobs:
  workflows:
    uses: L2jLiga/ha-addons/.github/workflows/addon-deploy.yaml@master
    secrets:
      DISPATCH_TOKEN: ${{ secrets.DISPATCH_TOKEN }}
