---
name: CI + Release

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  workflows:
    uses: L2jLiga/ha-addons/.github/workflows/addon-ci.yaml@master

  release:
    if: github.event_name != 'pull_request'
    needs:
      - workflows
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v4
      - id: version
        name: Detect version type
        run: |
          latest_version=`git tag | tail -1`
          is_major=`git log $latest_version..HEAD  --oneline | cut -d ' ' -f2 | grep '!:' | wc --lines`
          is_minor=`git log $latest_version..HEAD  --oneline | cut -d ' ' -f2 | grep 'feat:' | wc --lines`

          output='PATCH'

          if ! [ $is_major = '0' ]
          then
            output = 'MAJOR'
          else
            if ! [ $is_minor = '0' ]
              output = 'MINOR'
            fi
          fi

          echo "semver=$output" >> $GITHUB_OUTPUT
      - name: Automatic Semver Release
        uses: rui-costa/action-automatic-semver-releases@1.1.1
        with:
          TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          SEMVER: ${{ steps.version.outputs.semver }}
          LABEL: ""
