---
name: CI + Release

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  workflows:
    uses: L2jLiga/ha-addons/.github/workflows/addon-ci.yaml@master

  release:
    if: github.event_name != 'pull_request'
    needs:
      - workflows
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v4
      - name: Setup NodeJS
        uses: actions/setup-node@v4
      - name: Install coreutils
        run: sudo apt-get install -y coreutils
      - name: Install grep
        run: sudo apt-get install -y grep
      - name: Make the script files executable
        run: chmod +x get-last-version.sh
      - id: version
        name: Detect version type
        run: ./get-last-version.sh
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.version.outputs.semver }}
          release_name: Release ${{ steps.version.outputs.semver }}
          body: |
            Changes in this Release

            ${{ steps.version.outputs.changes }}
          draft: false
          prerelease: false
