---
name: CI + Release

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  workflows:
    uses: L2jLiga/ha-addons/.github/workflows/addon-ci.yaml@master

  release:
    if: github.event_name != 'pull_request'
    needs:
      - workflows
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v4
      - name: Setup NodeJS
        uses: actions/setup-node@v4
      - id: version
        shell: bash
        name: Detect version type
        run: |
          latest_version=`git tag | tail -1`
          changes="$(git log $latest_version..HEAD --oneline)"
          is_major=`git log $latest_version..HEAD --oneline | cut -d ' ' -f2 | grep '!:' | wc --lines`
          is_minor=`git log $latest_version..HEAD --oneline | cut -d ' ' -f2 | grep 'feat:' | wc --lines`

          increment='patch'

          if ! [ $is_major = '0' ]
          then
            increment='major'
          else
            if ! [ $is_minor = '0' ]
            then
              increment='minor'
            fi
          fi

          npm i -g semver
          version=`semver $latest_version -i $increment`

          echo "semver=$version" >> $GITHUB_OUTPUT
          echo "changes=<<EOF" >> $GITHUB_OUTPUT
          echo "$(git log $latest_version..HEAD --oneline)" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.version.outputs.semver }}
          release_name: Release ${{ steps.version.outputs.semver }}
          body: |
            Changes in this Release

            ${{ steps.version.outputs.changes }}
          draft: false
          prerelease: false
